### PR TITLE
Hardware compatibility improvements

### PR DESCRIPTION
**Pull request by Googulator**
Depends on #4.

### CODE REVIEW

**Comment by Googulator** [comment]
More fixes are coming soon to this PR, including the SI/DI confusion fix, as well as further hardware compatibility changes.

**Comment by rick-masters** [comment]
> More fixes are coming soon to this PR, including the SI/DI confusion fix, as well as further hardware compatibility changes.

I'm curious how this is going. Please let me know.

I'm having difficulty understanding the hex2tohex0 fix. I haven't found an example of a label that was not converted with the previous code. The purpose of the extra spaces was to align the comments after substitution in the same way that they were aligned prior to substitution. The stage2 hex0 files in this PR does not appear to be the result of running hex2tohex0 with your changes. When I run with the extra_spaces removed there are a lot of unaligned comments. So, I'm not sure what's going on. I can't see how you produced the aligned comments in the stage2 hex0 file.

Unrelated, to get this PR to work with live bootstrap as stage2 the starting LBA sector to read srcfs must be 166 not 165. This is near the beginning of the internalshell routine.

If you'd like I can commit the known fixes I have either in your PR branch or I can accept the PR and commit on top of that in my repo. You said you had other hardware compatibility so I don't know if I should wait for those first. Please let me know. Thank you for the work you are doing.

**Comment by Googulator** [comment]
The hex2tohex0 change was needed to handle situations where a label was shorter than the hex digits it expanded to, and there wasn't enough space around it for the hex to grow into. In this case, hex2tohex0 just left the label unswapped.

E.g. the following would trigger the bug:
```
:test
&test # comment to limit space
```

I did all of the label alignment by hand, because yes, as a side effect of the hex2tohex0 change, it generated misaligned labels - ugly, but better than generating broken hex0.

**Comment by rick-masters** [comment]
I see. I have a fix for that situation below. I think it is helpful to keep alignment feature to avoid having to do alignments by hand.

```
$ git diff hex2tohex0.py
diff --git a/hex2tohex0.py b/hex2tohex0.py
index 6f4a002..d05cd68 100644
--- a/hex2tohex0.py
+++ b/hex2tohex0.py
@@ -69,18 +69,26 @@ def print_replace(hex2path, hex0path, labels, base_address):
 
             for label, address in labels.items():
                 if len(label) + 1 - len(littleendian(address)) > 0:
+                    # the label is long and we need to pad the replaced address with extra spaces
                     extra_spaces = ' ' * (len(label) + 1 - len(littleendian(address)))
                     line = line.replace("&" + label + " ", littleendian(address) + extra_spaces + " ")
                 else:
+                    # the label is short and we need to remove extra spaces to match the length of the address
                     extra_spaces = ' ' * (len(littleendian(address)) - (len(label) + 1))
                     line = line.replace("&" + label + extra_spaces + " ", littleendian(address) + " ")
+                    # if there were no extra spaces make sure the replacement can work anyway
+                    line = line.replace("&" + label + " ", littleendian(address) + " ")
 
                 if len(label) + 1 - len(littleendian16(address)) > 0:
+                    # the label is long and we need to pad the replaced address with extra spaces
                     extra_spaces = ' ' * (len(label) + 1 - len(littleendian16(address)))
                     line = line.replace("$" + label + " ", littleendian16(address) + extra_spaces + " ")
                 else:
+                    # the label is short and we need to remove extra spaces to match the length of the address
                     extra_spaces = ' ' * (len(littleendian16(address)) - (len(label) + 1))
                     line = line.replace("$" + label + extra_spaces + " ", littleendian16(address) + " ")
+                    # if there were no extra spaces make sure the replacement can work anyway
+                    line = line.replace("$" + label + " ", littleendian16(address) + " ")
 
                 # XXX these functions could probably be unified!
                 line = relative8bit_replace(line, cur_address, label, address)
```

**Comment by rick-masters** [comment]
I realized later that my comment about changing the LBA offset to make live-bootstrap work was probably because I was using a different hex2tohex0.py and so my size was different than yours. You can ignore that part of my comment.

I'm still curious about the status of this PR. I'm assuming you're busy working on integrating your other changes into live-bootstrap. I'm hoping live-bootstrap will settle down soon so I can integrate the latest Fiwix code.

**Comment by rick-masters** [comment]
I just wanted to let you know that I plan on merging this PR tomorrow.
My plan is to accept the PR and then immediately reformat and commit using an improved hex2tohex0.py.
Then I'll apply the fixes (for DI to SI and proper RET) and fix the Makefile so that `make` completes successfully. 
I'll be reformatting first so that I don't mix formatting and functional commits.
Finally, I'll be adding a new test for multi-stage builds and some documentation.

If you are holding on to fixes or improvements that you would like to commit, I am willing to hold off until you go first so that you don't have to deal with merging my changes into yours. If so please let me know right away. Otherwise I plan to go ahead tomorrow.

**Pull request merged**
